### ISSUE TITLE
Ogg bitstream adherence

### ISSUE THREAD

**Issue by lnicola** [zaethan/opus_headers#2]
The code seems to go through the stream looking for the magic strings `OpusHead` and `OpusTags`. This is not desirable when e.g. trying to read a non-Opus file.

It might be better to follow the [Ogg container specification](https://tools.ietf.org/html/rfc3533):

 - read four bytes, check magic (`OggS`), reject if no match
 - read first page (might be more complicated)
 - decode Opus identification header, reject if no match
 - read next pages
 - decode Opus comment header, reject if no match

This is a bit more complicated if the file has multiple logical bitstreams, but I'm not sure how common those are.

**Comment by yboettcher** [comment]
I changed the parser to actually parse the Ogg headers instead of just seeking magic numbers.
I don't check the checksum though as I would need to store the Ogg payload twice to do so: first to calculate the checksum and once more to actually create the opus headers.
It also seems like long (text) comments are still part of a single page, since the maximum size of an Ogg page seems to be about 2^16 bytes or roughly 64kByte. One thing I just noticed while typing this is that an image might actually exceed that size... I will check that tomorrow. In that case I would just need to read multiple pages, combine their payload into a single vec and then build the comment header from that.

In case of multiple bitstreams, we should be able to just return a vector of OpusHeaders with one header per stream. However, that would force us to look through the entire file instead of just its beginning.

**Comment by lnicola** [comment]
According to the specs, the identification header needs to be on one page, but the tags can be longer. It's probably possible to construct files were the tags span multiple pages. The image sounds like a good way to test this.

I'd argue for returning only the first logical stream metadata to avoid reading the full file.

**Comment by yboettcher** [comment]
The Ogg parser now parses the payload as a Vec\<u8\>.
For the Identification Header, it uses the first Ogg pages' payload (luckily, &[u8] also implements Read) to parse the header.
For the Comment Header, the payloads of multiple Ogg pages are combined into a single Vec and then parsed.
The end of the comment header is found, when some Ogg pages' header_type does not contain the 0x01 bit.

Initial testing with some 1MB image file shows that this also works with large comments. Using a hex editor, it can be seen that the image is indeed split into multiple Ogg pages. I was also able to reconstruct the image file from the output that the parser creates, so I guess simply combining multiple payloads is correct.

**Comment by lnicola** [comment]
I haven't looked into detail, but it seems much better than before. I wanted to write about the header order, but you've fixed that, too. Thanks for putting up with me :-).

**Comment by yboettcher** [comment]
Well, I have to thank you for the time you invested to point out flaws in my implementation as well as improving this library with your own code :).
