### ISSUE TITLE
Opus body payload

### ISSUE THREAD

**Issue by Rikorose** [zaethan/opus_headers#6]
Thanks for this repo.

Do you have any plans for making the actual opus coded payload accessible via this crate? It seems that most of the functionality is already there; you would only need to continue reading [here](https://github.com/zaethan/opus_headers/blob/e083b85/src/lib.rs#L71) and store it in a vec as far as I understand.

**Comment by yboettcher** [comment]
I could add another function which returns only the payload.
The question is, how should that payload look like. One approach would be to just return all data / ogg pages after the headers as `Vec<u8>` or `Vec<OggPage>`. However this would probably be inconvenint for anyone who wants to process that data, as they would have to extract the actual opus payload from the ogg pages.
Another approach would be to extract the opus packets (see [here](https://tools.ietf.org/html/rfc6716), starting from page 13) from the ogg payloads and return a `Vec<OpusPacket>`, where OpusPacket would just be a newtyped `Vec<u8>`. 
I think the latter approach is the better one, unless I missed something.
To do that, we need to find the end of a packet / beginning of the next one. I will look into it :)

**Comment by Rikorose** [comment]
I would also favor the second solution since only libopus will then be needed to further decode the data.

**Comment by yboettcher** [comment]
Hi, I implemented packet extraction in the packet_parsing branch.

Right now, it returns an `OpusPackets` struct. That is just a newtyped `Vec<OpusPacket>`, whereas `OpusPacket` is just a newtyped `Vec<u8>`. However, I do not know how I could test/verify that this is actually the "correct" data. Looking at the contents of these packets, they seem to make sense. Most importantly, the config byte seems to be valid in all cases. Unfortunately, aside from the config byte, all of the data in the packets is just compressed audio.
So far, this implementation assumes that a packet ends, when the next ogg page is not a continuation of the previous page. While I am not entirely sure that this is right it does seem like it, as the spec says that the underlying ogg stream has to do "something" to communicate the length of the packets (section 3 [here](https://tools.ietf.org/html/rfc6716)). Also in the case of silent audio, all of the ogg pages were much shorter than in the case of a song. This further indicates that the end of a packet and the end of an ogg page are related.


Do you know of any way how I could verify that the packets I extract are indeed the correct opus packets?

**Comment by Rikorose** [comment]
You could compare the results to some other implementations like https://github.com/hraban/opus which is a wrapper around libopus and opusfile. For a simple test, decoding and listening to the audio could also be an option. For rust, there are some libopus wrappers e.g. https://github.com/Lakelezz/audiopus .

**Comment by yboettcher** [comment]
Hi, sorry for the long delay.
Upon trying to use it, I figured out that my original implementation of packet parsing was incorrect. Luckily, there is the [ogg library by RustAudio](https://github.com/RustAudio/ogg), which contains a PacketReader to do that properly. It **greatly** simplified other parts of the library as well, as I don't need to parse ogg pages to extract the headers anymore. This library can now focus on parsing the opus parts.
As for the opus data, I created a simple example which takes an opus file and writes the result into a wav. However this example only works for mono audio. I guess this is because audiopus returns the samples of the two channels in a different way than [hound](https://github.com/ruuda/hound) expects them...
The API now returns a `Result<Vec<Packet>>` whereas `Packet` is a re-export of the [`ogg::Packet`](https://docs.rs/ogg/0.7.1/ogg/struct.Packet.html). Each packet has a publicly accessible `data` field which is just a `Vec<u8>` and contains the actual opus data.
